[tools]
cmake = "latest"
github-cli = "latest"
fd = "latest"
bat = "latest"
ninja = "latest"
ripgrep = "latest"
uv = "latest"
neovim = "nightly"
tmux = "latest"
fzf = "latest"
node = "lts"
lazygit = "latest"
eza = "latest"
go = "latest"
codex = "latest"
claude-code = "latest"
copilot = "latest"
pnpm = "latest"
postgres = "16.14"

[settings]
trusted_config_paths = ['~/dotfiles/config/mise/config.toml']
